### ISSUE TITLE
[Feature Request] Reload images while reading.

### ISSUE THREAD

**Issue by shikiroot** [yuman07/EMHentai#7]
Sometimes the loading progress of some images will get stuck, and it will not recover even if exit the gallery and reopen. Network works fine, I think it's the problem of server side. Is it possible to add a button to manually reload current image or entire gallery?

**Comment by yuman07** [comment]
The current retry strategy for image downloads is unlimited, but you may have to wait a long time because you have to wait for a timeout before starting a new download. I can consider shortening the time the client considers a timeout, but I don't think it makes much sense to just add a retry button.

**Comment by yuman07** [comment]
This problem has been fixed. If an image times out for more than 10 seconds, it will automatically retry.
@shikiroot

**Comment by yuman07** [comment]
In addition, this 10s is my personal estimate. If you think it is not appropriate, you can adjust it in the file.
If you find a more suitable value, you can also give me feedback, thank you

<img width="526" alt="image" src="https://github.com/user-attachments/assets/8762ab94-6c05-4d58-a848-3151a2012716">
